### PR TITLE
Test for Learning about Pull Request 

### PR DESCRIPTION
**Pull request by anibaljrp**
- Change color of hero logo
- fix the old image of the hero
- Put webadas...

### CODE REVIEW

**Review by tapilew — CHANGES_REQUESTED** [review]
Thank you for fixing the broken link of the hero image.

But I don't like the "do webadas", please revert those changes. Just the fixed hero image is fine.

**Comment by anibaljrp** [comment]
ok

**Review by tapilew — COMMENTED** [review]
decent i guess

**Review by tapilew — APPROVED** [review]
nice

**Pull request merged**
